Repository unitedstack/kunkka, pull requests merged in 2018-05, with the labels that each got.

#266 router split brain and heat create bugfix
  client/applications/admin/modules/router/config.json
  client/applications/admin/modules/router/lang.json
  client/applications/admin/modules/router/model.jsx
  client/applications/admin/modules/router/pop/repair_split_brain/config.json
  client/applications/admin/modules/router/pop/repair_split_brain/index.js
  client/applications/admin/modules/router/request.js
  client/applications/dashboard/modules/heat-list/pop/create/base.jsx
  client/applications/dashboard/modules/heat-list/pop/create/style/index.less
  client/applications/dashboard/modules/router/lang.json
  client/applications/dashboard/modules/router/model.jsx
  client/applications/dashboard/modules/router/request.js
Labels: enhancement

#271 add global quota setting page for admin application
  client/applications/admin/config.json.sample
  client/applications/admin/locale/lang.json
  client/applications/admin/modules/block-storage-services/config.json
  client/applications/admin/modules/compute-services/config.json
  client/applications/admin/modules/global-quota/lang.json
  client/applications/admin/modules/global-quota/model.jsx
  client/applications/admin/modules/global-quota/request.js
  client/applications/admin/modules/global-quota/style/index.less
  client/applications/admin/modules/network-agents/config.json
  client/applications/admin/modules/orchestration-services/config.json
  client/applications/admin/modules/system-information/config.json
Labels: improvement

#273 fix quota-approval bug and modify quota setting check rule
  client/applications/admin/modules/project/lang.json
  client/applications/admin/modules/project/pop/modify_quota/index.js
  client/applications/admin/modules/project/pop/modify_quota/quota_pop.jsx
  client/applications/admin/modules/project/quota.jsx
  client/applications/admin/modules/quota-approval/detail/quota_detail.jsx
  client/applications/admin/modules/quota-approval/detail/style/index.less
  client/applications/admin/modules/quota-approval/model.jsx
  client/applications/dashboard/modules/overview/lang.json
  client/applications/dashboard/modules/overview/pop/modify_quota/index.js
  client/applications/dashboard/modules/overview/pop/modify_quota/quota_pop.jsx
  client/applications/dashboard/modules/overview/quota.jsx
  client/utils/get_quota_items.js
  client/utils/quota_validate.js
Labels: bugfix

#275 fix global quota setting bug
  client/applications/admin/modules/global-quota/lang.json
  client/applications/admin/modules/global-quota/model.jsx
Labels: bugfix

#276 add multi regions support for system information page's table
  client/applications/admin/modules/system-information/config.json
  client/applications/admin/modules/system-information/model.jsx
  client/applications/admin/modules/system-information/style/index.less
Labels: improvement

#278 remote login
  client/applications/login/model.jsx
  client/components/navbar/cluster.jsx
  client/components/navbar/index.jsx
Labels: enhancement

#283 update host overview
  client/applications/admin/config.json.sample
  client/applications/admin/model.jsx
  client/applications/admin/modules/host-overview/lang.json
  client/applications/admin/modules/host-overview/model.jsx
  client/applications/admin/modules/host-overview/request.js
  client/applications/admin/modules/host-overview/style/index.less
  client/applications/admin/modules/host/config.json
Labels: improvement

#284 cluster login bugfix
  client/applications/login/model.jsx
  client/components/navbar/cluster.jsx
Labels: bugfix

#287 login bugfix
  client/applications/login/model.jsx
Labels: bugfix
